import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import LayoutProvider from "@/providers/LayoutProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TCFP Quizzes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang='en'>
      <body className={`${inter.className} min-h-screen`}>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  </ClerkProvider>
  );
}
